export const KAFKA_PRODUCER_INSYNC_SERVICE_NAME =
    'KAFKA_PRODUCER_INSYNC_SERVICE';
export const KAFKA_PRODUCER_LEADER_SYNC_SERVICE_NAME =
    'KAFKA_PRODUCER_LEADER_SYNC_SERVICE';

export enum ENUM_KAFKA_PRODUCER_ACKS {
    INSYNC = 'INSYNC',
    LEADER_SYNC = 'LEADER_SYNC',
}
