export enum ENUM_AUTH_PERMISSIONS {
    API_KEY_READ = 'API_KEY_READ',
    API_KEY_CREATE = 'API_KEY_CREATE',
    API_KEY_UPDATE = 'API_KEY_UPDATE',
    API_KEY_ACTIVE = 'API_KEY_ACTIVE',
    API_KEY_INACTIVE = 'API_KEY_INACTIVE',
    API_KEY_RESET = 'API_KEY_RESET',
    API_KEY_UPDATE_DATE = 'API_KEY_UPDATE_DATE',

    SETTING_READ = 'SETTING_READ',
    SETTING_UPDATE = 'SETTING_UPDATE',
}
